services:
  web:
    build: .
    image: simple-app:latest
    container_name: simple-app
    environment:
      - PORT=8080
    ports:
      - "8080:8080"

  web2:
    build: .
    image: simple-app:latest
    container_name: simple-app
    environment:
      - PORT=8080
    ports:
      - "8081:8080"
